name: Download Excel File to GitHub

on:
  schedule:
    # Runs every day at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Manual trigger

jobs:
  download-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download Excel File
      run: |
        # Create data directory if it doesn't exist
        mkdir -p data
        
        # Download the file with timestamp
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        FILENAME="Active_fellows_PhD_status_${TIMESTAMP}.xlsx"
        
        # Try to download the file
        curl -L -o "data/${FILENAME}" "${{ secrets.SOURCE_URL }}" || {
          echo "Direct download failed, trying with user agent"
          curl -L -H "User-Agent: Mozilla/5.0" -o "data/${FILENAME}" "${{ secrets.SOURCE_URL }}"
        }
        
        # Also create a latest copy (overwrites previous)
        cp "data/${FILENAME}" "data/Active_fellows_PhD_status_latest.xlsx"
        
        # Check if file was downloaded successfully
        if [ -f "data/${FILENAME}" ] && [ -s "data/${FILENAME}" ]; then
          echo "File downloaded successfully: ${FILENAME}"
          ls -la data/
        else
          echo "Download failed or file is empty"
          exit 1
        fi
    
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "Update Excel file - $(date)" || exit 0
        git push
