name: Download Excel File (Working Version)

on:
  schedule:
    # Runs every day at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Manual trigger

jobs:
  download-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true
    
    - name: Download Excel File
      run: |
        # Create data directory if it doesn't exist
        mkdir -p data
        
        # Download the file with timestamp
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        FILENAME="Active_fellows_PhD_status_${TIMESTAMP}.xlsx"
        
        echo "Downloading from SharePoint..."
        curl -L \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" \
          -o "data/${FILENAME}" \
          "${{ secrets.SOURCE_URL }}"
        
        # Check if download was successful
        if [ -f "data/${FILENAME}" ] && [ -s "data/${FILENAME}" ]; then
          FILESIZE=$(stat -c%s "data/${FILENAME}")
          echo "✅ Download successful: ${FILENAME} (${FILESIZE} bytes)"
          
          # Create latest copy
          cp "data/${FILENAME}" "data/Active_fellows_PhD_status_latest.xlsx"
          
          # Verify it's actually an Excel file
          file "data/${FILENAME}"
          
          # Show first few bytes to confirm it's Excel format
          echo "File signature (should start with PK for Excel):"
          xxd -l 16 "data/${FILENAME}"
          
        else
          echo "❌ Download failed or file is empty"
          ls -la data/
          exit 1
        fi
    
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "Update Excel file - $(date)" || exit 0
        git push
